### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by PopularDemand** [wwcodedenton/wwcodedenton.github.io#6]
Create a cohesive brand for this site. While we are a child organization of WWCode international and WWCodeDFW, we're **Denton, TX, y'all**. Let's make this as original as we are.

We need a logo and color scheme and slogan and I'm sure even more.

If you're drafting up a logo or scheme, post a comment in this thread and attach the files so we can vote. In your pull request, place the files in the `assets/images` directory.

**Comment by PixelAtLarge** [comment]
Hi @PopularDemand - I just opened up a PR (#7) to address this issue. Here's my proposed logo:

![logo](https://cloud.githubusercontent.com/assets/10035318/19703313/5f988358-9ad1-11e6-8673-d548c669757c.png)

**Comment by PopularDemand** [comment]
Lovely. Thank you, Anna. If it gets selected, I'll be sure to attribute it.

**Comment by anant-dev** [comment]
Hi @PopularDemand - I just opened up a PR (#16) to address this issue. Here's my proposed logo:
![womenwhocode](https://cloud.githubusercontent.com/assets/13196029/19776188/bac56c4e-9c90-11e6-99fb-8b7844713748.png)

**Comment by PopularDemand** [comment]
Thank you!

**Comment by MADPT** [comment]
#20 add new logo

**Comment by PixelAtLarge** [comment]
@PopularDemand Hi! Now that Hacktoberfest is over, I was just curious if you had an update regarding this issue.

**Comment by PopularDemand** [comment]
Hey, @PixelAtLarge, thank for checking back. Sorry I haven't. The leadership actually said that we have to stick to the WWCode style guide and colors. So, for now all logo submissions are not being considered no matter how cool they are, and we are waiting for approval from the higher ups. Thanks.
